name: .NET

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./todo-backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: ${{env.working-directory}}
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: ${{env.working-directory}}
    


    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: .\coverage\**\coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'