name: .NET

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
       pwd
       ls
       dotnet restore ./todo-backend/todo-backend.sln
    - name: Build
      run: dotnet build ./todo-backend/todo-backend.sln --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
